apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "legacy-recommendation-engine"
  description: "Recommendation engine for Spotify's music player"
  annotations:
    github.com/project-slug: external-spotify-portal-demo/ai-recommendation-engine
    backstage.io/techdocs-ref: dir:.
    github.com/org: external-spotify-portal-demo
    github.com/repo: ai-recommendation-engine
spec:
  type: service
  lifecycle: production
  owner: "group:default/kubecon-squad"
